# Define the goal
geometry_msgs/Pose2D start
geometry_msgs/Pose2D goal

uint32 timeout # in ms
---
# Define the result
uint8 result

uint8 SUCCESS = 10
uint8 ERROR = 20
---
# Define a feedback message
duration processingTime
