# Define the goal
uint16 id
---
# Define the result
int16 result

int16 FINISHED=1
int16 ERROR=2
---
# Define a feedback message
uint8 percent_complete
uint16 id
int16 distance_path
int16 distance_recoil
time avoidance
time path
int16 average_vectors_speed
int16 mode

int16 FOLLOW = 1
int16 AVOID  = 2
int16 WAIT   = 3
