# Define the goal

---
# Define the result
uint16 status

uint16 STATUS_UNKNOWN = 1000
uint16 STATUS_FINISHED = 1001
uint16 STATUS_CANCELED = 1002
uint16 STATUS_INTERRUPTED = 1003

uint16 error

uint16 ERR_UNKNOWN = 0
uint16 ERR_NONE = 1
uint16 ERR_TRACKING_UNKNOWN = 100
uint16 ERR_TRACKING_OUT_OF_BOUND = 101
uint16 ARR_AVOIDANCE_UNKNOWN = 200

---
# Define a feedback message
uint8 percentComplete
duration processingTime
duration avoidanceTime
float32 trackPathError

uint16 mode

uint16 MODE_TRACKPATH = 2001
uint16 MODE_AVOID  = 2002
