# Work on a trusty VM
sudo: required
dist: trusty

# Allow only devel, master and branches containing a */ci-travis/* part
branches:
  only:
    - devel
    - master
    - /bob.*/
    - /stuart.*/
    - /.*\/ci-travis\/.*/

# Allow catkin_make to be ran
language:
  - python
cache:
  - apt
virtualenv:
  system_site_packages: true

before_install:
- openssl aes-256-cbc
  -K $encrypted_5a8f759d85bc_key
  -iv $encrypted_5a8f759d85bc_iv
  -in  ci-travis/travisci_rsa.enc
  -out ci-travis/travisci_rsa
  -d
- chmod 0600 ci-travis/travisci_rsa
- cp ci-travis/travisci_rsa ~/.ssh/id_rsa
# Check config
- $TRAVIS_BUILD_DIR/ci-travis/scripts/checkRequest.sh
# Do some test (eventually)
- $TRAVIS_BUILD_DIR/ci-travis/scripts/test.sh

install:
# Install packages dependencies and some dependencies from source
- $TRAVIS_BUILD_DIR/ci-travis/scripts/installDependencies.sh

# Configure environment (strongly needed for catkin)
- source ~/.bashrc
# Configure catkin workspace
- $TRAVIS_BUILD_DIR/ci-travis/scripts/installCatkinWorkspace.sh

script :
# Run catkin_make
- $TRAVIS_BUILD_DIR/ci-travis/scripts/build.sh

after_success:
# Deploy doxygen documentation
- $TRAVIS_BUILD_DIR/ci-travis/scripts/publishDoxygen.sh