branches:
  only:
    - devel
    - doxygen
    - tavis
brefore_install:
- openssl aes-256-cbc
  -K $encrypted_5a8f759d85bc_key
  -iv $encrypted_5a8f759d85bc_iv
  -in  ci-travis/travisci_rsa.enc
  -out ci-travis/travisci_rsa
  -d
- chmod 0600 ci-travis/travisci_rsa
- cp ci-travis/travisci_rsa ~/.ssh/id_rsa
install:
- sudo apt-get update -qq
- sudo apt-get install --yes doxygen graphviz
script : gcc -v
after_success:
- ./ci-travis/publish-doxygen.sh

