uint8 C0 = 0
uint8 C1 = 1
uint8 C2 = 2
uint8 C3 = 3

uint8 RING_BLUE   = 1
uint8 RING_GREEN  = 2
uint8 RING_ORANGE = 3
uint8 RING_YELLOW = 4

uint8 BASE_RED    = 1
uint8 BASE_BLACK  = 2
uint8 BASE_SILVER = 3

uint8 CAP_BLACK = 1
uint8 CAP_GREY  = 2


uint32 id
uint8 complexity

uint8 base_color
uint8[] ring_colors
uint8 cap_color

uint32 quantity_requested
uint32 quantity_delivered_cyan
uint32 quantity_delivered_magenta

uint32 delivery_period_begin
uint32 delivery_period_end

uint32 delivery_gate
