HSV_threshold:
  value: {max: 255, min: 0}
  enabled: true
opening:
  enabled: true
  size: 8
  iteration: 3
closing:
  enabled: true
  size: 8
  iteration: 3
image_result:
  list: {"Flux_origine": "/image_raw", "Image_resultat": "/feu_tricolore/img_result compressed"}