## Goal definition

int8 BS = 0
int8 RS = 1
int8 CS = 2
int8 DS = 3

int8 type

int8 IN  = 100
int8 OUT = 101

int32 side

int8 S1       	= 10
int8 S2       	= 20
int8 S3       	= 30
int8 CONVEYOR 	= 40
int8 LIGHT    	= 50
int8 LANE_RS  	= 60
int8 LIGHT_OLD	= 70

int8 parameter

# Special order. Final Approach distance will be controlled by "navigation/finalApproachControl"(std_msgs/Float32) topic
# NB: LIGHT parameter is not allowed for this mode
bool controlled_approach

---

## Result definition

bool success

int8 UNKNOWN       = 0
int8 OBSTACLE_HIT  = 1
int8 OBSTACLE_NEAR = 2
int8 COMPLETE_SCAN = 3
int8 INVALID_ORDER = 4
int8 ARTAG_LOST    = 5

int8 state

---

## Feedback
int32 percent_complete

# Distance in meters from robot center to machine
float32 distance_to_machine

# Asserv errors
float32 errorX
float32 errorY
float32 errorYaw
